README.org ---  description



Copyright (C) 2019 Roman V. Prikhodchenko



Author: Roman V. Prikhodchenko <chujoii@gmail.com>

  This file is part of c-artificial-neural-network.

  c-artificial-neural-network is free software: you can redistribute it and/or modify
  it under the terms of the GNU General Public License as published by
  the Free Software Foundation, either version 3 of the License, or
  (at your option) any later version.

  c-artificial-neural-network is distributed in the hope that it will be useful,
  but WITHOUT ANY WARRANTY; without even the implied warranty of
  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
  GNU General Public License for more details.

  You should have received a copy of the GNU General Public License
  along with c-artificial-neural-network.  If not, see <http://www.gnu.org/licenses/>.


  Documentation is licensed under a Creative Commons
  Attribution-ShareAlike 3.0 Unported License.

* Keywords:
library growing neural gas utility factor
  

* Description:
simple artificial neural network "growing neural gas with utility factor" library
  
  
* Usage:

* History:
Initial project version began about 2019-12(Dec)-25
Project based on lisp (scheme) version: lisp-artificial-neural-network

* Dependences:
+ [[https://www.graphviz.org/][media-gfx/graphviz]] [[https://gitlab.com/graphviz/graphviz/][src]] Open Source Graph Visualization Software
  LICENSE="CPL-1.0"
+ any TeX distribution (MetaPost - image generator), for example:
  [[http://tug.org/texlive/][app-text/texlive]] A complete TeX distribution
  LICENSE=" CC-BY-SA-4.0 GPL-1 GPL-2 GPL-3+ LGPL-2 LPPL-1.3 MIT public-domain TeX-other-free "
+ [[http://www.gnuplot.info/][sci-visualization/gnuplot]] Command-line driven interactive plotting program
  LICENSE="gnuplot bitmap? ( free-noncomm )"
+ [[https://github.com/rvoicilas/inotify-tools/wiki][sys-fs/inotify-tools]] A set of command-line programs providing a
  simple interface to inotify
  LICENSE="GPL-2"
* Code:
